### ISSUE TITLE
km200.0.dhwCircuits.dhw1.chargeDuration - wrong data type

### ISSUE THREAD

**Issue by EvilEls** [frankjoke/ioBroker.km200#21]
Hi,
trying to **set** this value I get error:

`Set KM200 err: 'request for  /dhwCircuits/dhw1/chargeDuration had status 400/Bad  Request other than supported 200,204'
`
Data type has to be set to `number` to make it work.

**Comment by frankjoke** [comment]
Ok, I found the error which was that the data is shown in nice time format and stored as string instead of a number.
I removed this feature which means it will be displayed only a number and you can change this number then.
I post the current test version for next version here on git but not on npm so far, it still needs to get some other options...
